/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gradepredictorprototype;

import java.awt.event.KeyEvent;

/**
 *
 * @author kingt
 */
public class AboutYou extends javax.swing.JFrame {

    /**
     * Creates new form AboutYou
     */
    public AboutYou() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        nameFld = new javax.swing.JTextField();
        usernameFld = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setText("About You:");

        nameFld.setText("Name");
        nameFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameFldMouseClicked(evt);
            }
        });

        usernameFld.setText("Username");
        usernameFld.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFldFocusGained(evt);
            }
        });
        usernameFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameFldMouseClicked(evt);
            }
        });
        usernameFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFldActionPerformed(evt);
            }
        });
        usernameFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameFldKeyPressed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(432, 432, 432)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(433, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameFldMouseClicked
        nameFld.selectAll(); //automatically selects all text when clicked
    }//GEN-LAST:event_nameFldMouseClicked

    private void usernameFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameFldMouseClicked
        usernameFld.selectAll();//automatically selects all text when clicked
    }//GEN-LAST:event_usernameFldMouseClicked

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        if (ValidationRoutines.presenceCheck(nameFld.getText()) //checks name field is not empty
                    && ValidationRoutines.presenceCheck(usernameFld.getText()) //checks username field is not empty
                    && !nameFld.getText().equals("Name") //checks name field has not been left unchanged
                    && !usernameFld.getText().equals("Username") //checks username field has not been left unchanged
                    && ValidationRoutines.lengthCheck(0,nameFld.getText(),32) //checks name will fit in database
                    && ValidationRoutines.lengthCheck(0,usernameFld.getText(),32)) { //checks username will fit into database
                    
            User user = GradePredictorPrototype.getUser(); //gets the current user
            DatabaseManipulation.aboutYou(nameFld.getText(), usernameFld.getText(), user); //sets the users name and username to new name
            GradePredictorPrototype.setNames(usernameFld.getText(), nameFld.getText(), user.getType()); //sets local variables storing name and username to new name
            if (user.getType() == 0) { //checks if current user is a teacher
                new TeacherProfile().setVisible(true); //if user is teacher opens teacher profile                
                this.dispose(); //and closes this form
            } else if (user.getType() == 1) { //checks if current user is a student
                new StudentProfile().setVisible(true);//if so opens student profile
                this.dispose();//and closes this form
            }
        } else { //if validation rouitines were failed
            User user = GradePredictorPrototype.getUser(); //gets the current user
            if (user.getType() == 0) {
                new TeacherProfile().setVisible(true); //goes into teacher profile if user is a teacher
                this.dispose();
            } else if (user.getType() == 1) {
                new StudentProfile().setVisible(true); // goes into student profile if user is a student
                this.dispose();
            }
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void usernameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFldActionPerformed

    private void usernameFldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameFldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { //method checks if enter key is presses
            if (ValidationRoutines.presenceCheck(nameFld.getText()) //if it is, it continues on in the same way as the 'saveButtonActionPerformed' method 
                    && ValidationRoutines.presenceCheck(usernameFld.getText()) 
                    && !nameFld.getText().equals("Name") 
                    && !usernameFld.getText().equals("Username")
                    && ValidationRoutines.lengthCheck(0,nameFld.getText(),32)
                    && ValidationRoutines.lengthCheck(0,usernameFld.getText(),32)) {
                    
            User user = GradePredictorPrototype.getUser();
            DatabaseManipulation.aboutYou(nameFld.getText(), usernameFld.getText(), user);
            GradePredictorPrototype.setNames(usernameFld.getText(), nameFld.getText(), user.getType());
            if (user.getType() == 0) {
                new TeacherProfile().setVisible(true);
                this.dispose();
            } else if (user.getType() == 1) {
                new StudentProfile().setVisible(true);
                this.dispose();
            }
        } else {
            User user = GradePredictorPrototype.getUser();
            if (user.getType() == 0) {
                new TeacherProfile().setVisible(true);
                this.dispose();
            } else if (user.getType() == 1) {
                new StudentProfile().setVisible(true);
                this.dispose();
            }
        }
        }
    }//GEN-LAST:event_usernameFldKeyPressed

    private void usernameFldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFldFocusGained
        usernameFld.selectAll();//automatically selects all text when tabbed onto
    }//GEN-LAST:event_usernameFldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutYou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutYou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutYou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutYou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutYou().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField nameFld;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextField usernameFld;
    // End of variables declaration//GEN-END:variables
}
